- name: Running APT to update the system.
  hosts:  debian
  tasks:
    - name: Upgrade all packages to the latest version.
      apt:
        upgrade: full
        autoremove: yes
      become: yes

- name: Running DNF to update the system.
  hosts:  rhel
  tasks:
    - name: Upgrade all packages to the latest version.
      dnf:
        name: "*"
        state:  latest
      become: yes

- name: Running Zypper to update the system.
  hosts:  suse
  tasks:
    - name: Upgrade all packages to the latest version.
      zypper: 
        name: "*"
        state:  latest
      become: yes
    - name: Apply all security patches.
      zypper:
        name: "*"
        state: latest
        type: patch
      become: yes