- name: Updating Windows Servers
  hosts:  windows
  remote_user:  hcadmin
  tasks:  
    - name: Downloading Windows Updates.
      win_updates:  
        state:  downloaded
    - name: Installing Windows Updates.
      server_selection: managed_server
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - Updates
        state: installed
        register: update_result
        log_path: c:\ansible_update.txt