- name: Updating Windows Servers
  hosts:  windows
  remote_user:  hcadmin
  tasks:  

    - name: Installing Windows Updates.
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      state: installed
      register: update_result
      log_path: c:\ansible_update.txt