- name: Updating Windows Servers
  hosts:  windows
  remote_user:  hcadmin
  tasks:  
    - name: Downloading Windows Updates.
      win_updates:  
        state:  downloaded
    - name: Installing Windows Updates.
      win_updates:
        state: installed
        register: update_result
        log_path: c:\ansible_update.txt