- name: Updating Windows Servers
  hosts:  windows
  remote_user:  hcadmin
  ansible_connection: ssh
  ansible_shell_type: cmd
  tasks:  
    - name: Running Windows Update.
      win_updates:  
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups