- name: Updating Windows Servers
  hosts:  windows
  remote_user:  hcadmin
  tasks:  
    - name: Running Windows Update.
      win_updates:  
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups